### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [maticstric/mark-twain_roughing-it#1]
CSS:

- `#chapter-77 figure > span` does not need text-indent; also let's make the margin .5em so we maintain a .5 visual rhythm

- Some CSS seems commented out?

- We never want to have classes that are there just to apply styles, like the `center` class. All of these can be handled differently without a `center` class:

    - In chapter 65 and 78, the centered quote should be a blockquote and you can target `#chapter-65 blockquote` and `#chapter-78 blockquote`

    - Likewise chapter 70 center can be replaced with `#chapter-70 blockquote:last-of-type p:first-child`

    - Chapter 71 should also be in a blockquote which can be targeted. Also in this section, CAPTAIN JAMES COOK should be in small caps. You can do this with `<b>`.

- The `small-font` class can be replaced with `<small>`

- In chapter 16 you use flexbox to style the two column signatures. This requires a child `<div>` which is markup cruft to support visual styling. It occurs to me that we can probably achieve this same effect with CSS grid, while removing the cruft `<div>`s. Any reader that supports flex will likely support grid, and any vice versa, so I'm not worried about reader support. And if unsupported they will both degrade in the same way. Can you look in to that?

- In appendix C, let's wrap the long quotation in `<blockquote>`. You can style it so that it has 0 margin. That way the `<header>` elements will be headers of the quotation, and not headers of the chapter. This will also allow you to remove the `right-align` class and replace it with something like `#appendix-c > blockquote p:first-child`.

- You can add an se-lint-ignore.xml file to ignore the error about measurements, it is clearly an incorrectly matched rule

- I think you can remove italics from `alias`, it was likely italicized as a kind of Latinism but it not longer is

- Totally obscured words should use the three-em-dash character; I see at least one that is a two-em-dash: `Then, by ⸺, I brand`

- Appendix C line 89: Italics should go inside brackets, not outside. See lines 59, 89, and others?

- Chapter 4: Single quote goes inside italics: `’<i>dobies</i>`

- Chapter 79: Moral should not be in a header. It's probably best to put it in a `<p><b>` and target it for centering with `nth-last-child(2)`

- If a section only has a title, and no further heading content, then `<header>` is not necessary. For example in appendix A and B.

- Chapter 53: Put this story in a blockquote as well, and you can also target it for 0 margin

- Chapter 51: The heading of the poem goes within the blockquote

- The prefatory is frontmatter, so it should go before the half title. You have to edit the book spine, then run print-toc again.

- In the endnotes, when an endnote contains an ending signature, it goes in a `<cite>` element. The em dash goes within `<cite>` and there is a space before the element. For example notes 6, 9, and more.

- Endnote 18: I would italicize `tah-boo` with `<i>`

- Endnote 20: Remove brackets around M. T.

- Colophon: 

    - If you prefer to be anonymous, use `<b class="name">` around your name and not a link to SE
    
    - Quote in painting name needs to be rsquo

- `se clean` makes some changes, please run it after you're done

**Comment by maticstric** [comment]
Don't know exactly how to format my questions so I did it like this:

- Done!
- CSS is commented out because there's a bug with `se build`: it breaks with media queries ([discussion](https://groups.google.com/g/standardebooks/c/P1iMLgbgG6o/m/KFn-P_xWAgAJ)). We want the css in once it's fixed, so I decided to comment it out for now and then we can simply uncomment it (note that the commented out css is now different since you wanted to use grid).
- Should be done.
  - Done!
  - Done but had to use `#chapter-70 blockquote:last-of-type > p:first-child` because the "Yours," was also being selected
  - Done!
- Done!
- I have no experience with css grid but I did manage to do get it working. Sort of. I pushed it onto git so you can check it out. My only problem is that the two columns aren't "touching" each other. I wanted both of them to align themselves to each other on the right, but instead the both take half the space available, and align themselves to the right of that half. Probably not explaining it well but if you quickly add `border: 1px solid black;` to everything, it'll make more sense. I would need some help with this.
- Done but I made the css `margin-left: 0` and `margin-right: 0` not just `margin: 0` because otherwise the signature on the bottom would look too close to the next paragraph.
- Done!
- Done!
- I decided to just use a two-em-dash because Appendix C has a lot of these if you look [here](https://archive.org/details/roughingit02twai/page/584/mode/1up) or [here](https://archive.org/details/roughingit02twai/page/585/mode/1up) or [here](https://archive.org/details/roughingit02twai/page/589/mode/1up). I realized a lot of those are actually supposed to be curse words "bleeped" out for comedic effect but also partially a stylistic choice by either Twain or Conrad Wiegand (the latter being why I decided not to replace them with three-em-dashes). If you want to, I can replace all of them to three-em-dashes.
- Done!
- Done!
- Done!
- Done!
- Done but again I made the css `margin-left: 0` and `margin-right: 0` because the top/bottom looked to close to the paragraphs before/after them.
- Done!
- Done!
- Done!
- Done!
- Done!
- Done!
  - Done!
  - Done!
- Done!

**Comment by acabal** [comment]
Great, thanks.

Toolset 1.5.9 was just released which fixes the crash on media queries, so you can remove the comments from that CSS.

I don't know much about CSS grid either as it's fairly new. I assume it can do what we need, it will just take some massaging. Maybe you can post to the mailing list to ask if anyone has more experience. This would seem like an especially simple case.

Please replace all totally obscured words with three em dashes, which is SE style.

**Comment by maticstric** [comment]
All done! This should be ready for release. Thanks again for the help.
